resources:
- repo: self
trigger:
- build-refactor

jobs:
- job: PythonTests
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-16.04
  container: mhamilton723/mmlspark-build:0.17.4
  steps:
    - task: Bash@3
      displayName: 'Python Tests'
      inputs:
        targetType: inline
        script: 'ls && pwd && sbt testPython'
        failOnStderr: true
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/test-reports/*.xml'
      inputs:
        testResultsFiles: 'target/**/generated/test_results/python/*.xml'
        failTaskOnFailedTests: true
      condition: succeededOrFailed()
