resources:
- repo: self
trigger:
- build-refactor

jobs:
- job: PythonTests
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-16.04
  container: 
    image: mhamilton723/mmlspark-build:0.17.4
    options: "--name cicontainer -v /usr/bin/docker:/tmp/docker:ro"
  steps:
    - script: /tmp/docker exec -t -u 0 cicontainer sh -c "apt-get update && apt-get -o DPkg::Options::="--force-confold" -y install sudo"
      displayName: Install sudo
    - task: Bash@3
      displayName: 'Python Tests'
      inputs:
        targetType: inline
        script: 'ls && pwd && sudo -H sbt testPython'
        failOnStderr: true
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/test-reports/*.xml'
      inputs:
        testResultsFiles: 'target/**/generated/test_results/python/*.xml'
        failTaskOnFailedTests: true
      condition: succeededOrFailed()
